{...}:
{
  imports = [
    ./arandr.nix
    ./bat.nix
    ./browser.nix
    ./btop.nix 
    ./dev.nix
    ./fish.nix
    ./git.nix
    ./gnome.nix 
    ./gtk.nix
    ./helix.nix
    ./hyprland
    ./kitty.nix
    ./files.nix 
    ./mpv.nix
    ./office.nix
    ./rofi.nix
    ./thunderbird.nix
    ./todo.nix
    ./typset.nix
    ./swaylock.nix
    ./swaync/swaync.nix
    ./swayosd.nix
    ./user.nix
    ./viewnior.nix
    ./waybar
    ./xdg-mimes.nix
  ];
}
