{...}:
{
  imports = [
    ./arandr.nix
    ./autoclicker.nix
    ./bat.nix
    ./browser.nix
    ./btop.nix 
    ./chat.nix
    ./dev.nix
    ./fish.nix
    ./git.nix
    ./gnome.nix 
    ./gtk.nix
    ./helix.nix
    ./hyprland
    ./kitty.nix
    ./files.nix 
    ./mail.nix
    ./mpv.nix
    ./music.nix
    ./neofetch.nix
    ./nextcloud.nix
    ./office.nix
    ./rofi.nix
    ./todo.nix
    ./pinta.nix
    ./typset.nix
    ./steam.nix
    ./swaylock.nix
    ./swaync/swaync.nix
    ./swayosd.nix
    ./syncthing.nix
    ./user.nix
    ./viewnior.nix
    ./waybar
    ./whichkey.nix
    ./xdg-mimes.nix
  ];
}
